baseURL = "https://r-indonesia.id"
languageCode = "en-us"
title = "R Indonesia"
description = "Blog Kolaborasi Komunitas R Indonesia"
theme = "min_night"
disqusShortname = "aswansyahputra"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "public/"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    author = "Kontributor"
    description = "Blog Kolaborasi Komunitas R Indonesia"
    logo = "favicon/android-chrome-192x192.png"
    githubUsername = "indo-r"
    accent = "#386890" # dark colors do best
    backgroundColor = "#f5f5f5"
    font = "Mina" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "lakeside-light" # make this match accent
    highlightLanguages = ["r", "bash", "go"]

# adjust these as you see fit
[[menu.main]]
    url = "/"
    name = "Beranda"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Tulisan"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Proyek"
    weight = 3
    
[[menu.main]]
    url = "/tags/"
    name = "Tags"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://github.com/indo-r"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://t.me/GNURIndonesia"
    name = "telegram"
    weight = 4
